version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: payments_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./payments_app:/code/payments_app
      - ./tests:/code/tests

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  worker:
    build: .
    restart: always
    depends_on:
      - rabbitmq
    env_file:
      - .env
    volumes:
      - ./payments_app:/code/payments_app
    command: celery -A payments_app.tasks worker -l info

volumes:
  postgres_data:
